AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Lambda function that takes in an image in Base64 then returns an emotion
Resources:
  lambdarekognition:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: >-
        A Lambda function that takes in an image in Base64 then returns an
        emotion
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::041301154326:role/lambda_rekognition'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: POST
